name: 'demo'
version: '1.0.0'
config-version: 2


profile: 'default'
models:
    demo:
test-paths: ["tests"]
source-paths: ["models"]

tests:
  <resource-path>:
    +enabled: true 
    +tags: "my_tag"
    +error_if: '!=2920'